from typing import Literal

STATUS_TYPES = Literal['FAILED', 'SUCCEEDED', 'SUBMITTED', 'RUNNING', 'RUNNABLE', 'PENDING', 'STARTING']
LOGGING_LEVELS = Literal['CRITICAL', 'FATAL', 'ERROR', 'ERROR', 'WARN', 'WARNING', 'INFO', 'DEBUG', 'NOTSET']
